name = "thumr-dev"
main = "worker.ts"
compatibility_date = "2024-12-20"

[build]
command = "npm run build"

[assets]
directory = "./dist"

[env.dev]
workers_dev = true

[vars]
# AWS Cognito Configuration
VITE_AWS_USER_POOL_ID=us-east-1_2uwdcZRLa
VITE_AWS_USER_POOL_CLIENT_ID=58m59u2n4ddoldec2rs4oiuc6i
VITE_AWS_REGION=us-east-1

# API Endpoints
VITE_API_PLANTS_READ=https://dzakzltsq4.execute-api.us-east-1.amazonaws.com/default/readPlantsData
VITE_API_PLANTS_WRITE=https://dzakzltsq4.execute-api.us-east-1.amazonaws.com/default/writePlantsData
VITE_API_PLANTS_UPDATE=https://dzakzltsq4.execute-api.us-east-1.amazonaws.com/default/updatePlantData
VITE_API_USERS_READ=https://dzakzltsq4.execute-api.us-east-1.amazonaws.com/default/readUsersData
VITE_API_USERS_WRITE=https://dzakzltsq4.execute-api.us-east-1.amazonaws.com/default/writeUsersData
VITE_API_USERS_UPDATE=https://dzakzltsq4.execute-api.us-east-1.amazonaws.com/default/updateUserData

# IMPORTANT: This file contains sensitive information
# Never commit this file to version control
